# -*- coding: utf-8 -*-
"""DAY_11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YQCi160jo32mNdw9O-JC_1a48UNXSwzq
"""

# The BlackJack Capstone Project -->

# In this lesson we'll be using all skills acquired till now to complete the BlackJack Capstone Project

# Blackjack / 21
# cards -- add upto the largest number less than 21
# if they're more that 21 -- lose -> bust

# Our Blackjack House Rules

## The deck is unlimited in size.
## There are no jokers.
## The Jack/Queen/King all count as 10.
## The the Ace can count as 11 or 1.
## Use the following list as the deck of cards:
## cards = [11, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10]
## The cards in the list have equal probability of being drawn.
## Cards are not removed from the deck as they are drawn.
## The computer is the dealer.

# Head over to this link for the final project

https://replit.com/@AqsaAshfaq07/BlackJack-Capstone-Project?v=1