# -*- coding: utf-8 -*-
"""DAY_16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGiWXs0ktoZgbkeiV5KaPlfcZSRuQF0Z
"""

# Procedural Programming
# -> One procedure leads to another one in a top-down appraoch
# Increased Complexity due to increased relationships
# Can not be used to create larger and complex systems

# Object Oriented Programming
# -> Split the task in multiple chunks - work on the modules independtly - integrate the whole thing
# More usable components
# Models real world objects

# How to Use OOP

# # To model a Single Object - we need to know

# 1 - ATTRIBUTES (variables)
# # what it HAS -> name, money ...

# 2 - METHODS (functions)
# # 2 - what is DOES -> code, eat ...

!pip -vvv install prettytable



# Creating object of the class from pretty table

from prettytable import PrettyTable
table = PrettyTable()
print(table)

# Adding data to the table

table.add_column("Pokemon Name", ["Pikachu", "Squirtle", "Charmander"])
table.add_column("Type", ["Electric", "Water", "Fire"])
print(table)

# Changing Attributes

table.align = 'r' # change the allignment to the right
print(table)

